name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sakshi 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4' 
          
      # Install dependencies for frontend
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Install dependencies for backend
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # Start backend for testing
      - name: Run backend
        working-directory: backend
        run: npm start
